import '@fontsource/montserrat/400.css';
import '@fontsource/montserrat/600.css';
import '@fontsource/montserrat/500.css';

// use theme add new file theme where theme = {
//  fontFamily: ...
//  fontWeights: ...
//    colors: ...
// }
